name: Proof of Concept
favicon: null
layout_spectrum: 0.7981749200262129
typography_spectrum: 0.32637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dc2e27'
    - '#a52138'
    - '#6b2349'
    - '#e3592b'
    - '#2c245f'
  brandStrength: 0.8735536185558885
  lightness: 0.12950892304070294
  saturation: 0.14954517921432853
  rhythmicContrast: 0.17211770708672702
purpose: []
